nxp-s32g: pfe: update to fix the build error
Issue: LINCD-9364

This patch is to fix the following build error:

  error: the comparison will always evaluate as 'true' for the address of 'macaddr' will never be NULL [-Werror=address]
     942 |         if (netif->cfg->macaddr && is_valid_ether_addr(netif->cfg->macaddr))
         |             ^~~~~

Signed-off-by: Zhantao Tang <zhantao.tang@windriver.com>