nxp-s32g: conf: move unsigned kernel for LAT secure boot
Issue: LINUXEXEC-24056

The commit c99573ed2bb6 ("conf/machine/nxp-s32g.conf: add unsigned kernel
back for LAT secure boot") append unsigned kernel into KERNEL_IMAGETYPES
when secboot enabled, but it used HSE_SEC_ENABLED to check if secboot
enabled, which will be used in normal boot too. Then if HSE enabled, there
will be following build error：

  ERROR: linux-yocto-xxx do_package: QA Issue: kernel-image-image is listed in PACKAGES multiple times, this leads to packaging errors. [packages-list]
  ERROR: linux-yocto-xxx do_package: Fatal QA errors were found, failing task.

So move the unsigned kernel into KERNEL_IMAGETYPES when secboot enabled indeed.

Signed-off-by: Zhantao Tang <zhantao.tang@windriver.com>