nxp-s32g: fix check layer issue on can-utils bbappend
Issue: LIN1023-3068

Since the can-utils bbappend is based on meta-openembedded layer, and the
yocto-check-layer complains that:
  ERROR: No recipes in default available for:
  .../layers/nxp-s32g/recipes-extend/socketcan/can-utils_2023.03.bbappend

So move the bbappend into dynamic-layers to fix the above issue.

Signed-off-by: Zhantao Tang <zhantao.tang@windriver.com>