atf-s32g: Add BUILD_LDFLAGS to HOSTCC
Issue: LINCD-8627

It uses HOST_CC as ld which doesn't enable uninative, and causes the following
error on CentOS 7:

/path/to/x86_64-wrlinuxsdk-linux/bin/ld: /lib64/libpthread.so.0: undefined reference to `__libc_dl_error_tsd@GLIBC_PRIVATE'

Add BUILD_LDFLAGS to HOSTCC will fix the problem

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>