nxp-s32g: conf: add PREFERRED_PROVIDER for u-boot-tools-native to fix build issue
Issue: LINUXEXEC-27398

This patch is to fix the following error:

  WARNING: u-boot-tools-native is not in the recipe list, figuring out complete list of recipes...
  ERROR: Nothing PROVIDES 'u-boot-tools-native' (but xxx/atf-s32g_2.5.bb DEPENDS on or otherwise requires it)
  ...

  You may also have to add: BB_NO_NETWORK = '0'
  ERROR: Required build target 'atf-s32g' has no buildable providers.
  Missing or unbuildable dependency chain was: ['atf-s32g', 'u-boot-tools-native']

Specify the PREFERRED_PROVIDER for u-boot-tools-native can fix it.

Signed-off-by: Zhantao Tang <zhantao.tang@windriver.com>