nxp-s32g2xx: pfe: update to fix build error of pfe firmware fetch failure
Issue: LINCD-6886

The pfe firmwares path settings have changed to simplify the usage,
but if users foget to give the firmwares location and build the pfe
package, then the following errors will show:

  ERROR: Fetcher failure for URL: 'file://./s32g_pfe_class.fw'. Unable to fetch URL from any source.

This patch is to fix the above issue.

Signed-off-by: Zhantao Tang <zhantao.tang@windriver.com>