nxp-s32g2xx: conf/machine: modify tune file path to fix build error
Issue: LINCD-6595

Due to the rename of tune-cortexa53.inc from
	conf/machine/include/tune-cortexa53.inc
to
	conf/machine/include/arm/armv8a/tune-cortexa53.inc

Modify the machine/nxp-s32g2xx.conf of nxp-s32g2xx bsp to
compatible with the tune file to fix the following parse error:

	ERROR: ParseError at /layers/nxp-s32g2xx/conf/machine/nxp-s32g2xx.conf:6:
	Could not include required file conf/machine/include/tune-cortexa53.inc

Signed-off-by: Zhantao Tang <zhantao.tang@windriver.com>