nxp-s32g: atf: update to fix secboot "invalid fip start offset" failure
Issue: LIN1023-5083

The atf recipe has been updated to compatible with SDK BSP40, and to
make the secure boot feature works normally, the deploy task should
be after do_install, because deploy task depends on the do_install()
output binary, or else there will be following failure:

  # hse-secboot -s -k /boot/rsa2048_public.pem -d /dev/mmcblk0
  [INFO] Setting up secure boot
  libhse: initialized, firmware status 0x0920
  [INFO] Retrieving IVT from device /dev/mmcblk0
  [INFO] Enabling MUs
  [INFO] Did not find previous SYSIMG, formatting NVM and RAM key catalogs
  [INFO] Importing RSA public key into NVM key catalog
  [INFO] Generating Secure Memory Region entry
  ERROR: invalid fip start offset!
  [ERROR] Failed to allocate space for FIP header
  ERROR: fip smr entry install failed!
  libhse: closed

So correct the sequence of tasks to fix the above failure.

Signed-off-by: Zhantao Tang <zhantao.tang@windriver.com>