nxp-s32g: atf: update to fix fuzz detected issue
Issue: LIN1024-2814

This patch is to fix following QA issue:

  ERROR: atf-s32g-2.10-r0.vr2401 do_patch: QA Issue: Fuzz detected:

  checking file fdts/s32gxxxa-evb.dtsi
  Hunk #1 succeeded at 18 with fuzz 2 (offset 1 line).

  patching file fdts/s32gxxxa-evb.dtsi
  Hunk #1 succeeded at 18 with fuzz 2 (offset 1 line).

  The context lines in the patches can be updated with devtool:

      devtool modify atf-s32g
      devtool finish --force-patch-refresh atf-s32g <layer_path>

  Don't forget to review changes done by devtool!

Signed-off-by: Zhantao Tang <zhantao.tang@windriver.com>