nxp-s32g: wic: dmverity: add IMAGE_NAME_SUFFIX for sourceparams to fix build failure
Issue: LIN1024-2558

Since the wic image name style is changed in LTS24, so update
sourceparams by adding IMAGE_NAME_SUFFIX variable to fix build failure,
or else, there will be following error when building:

  wic.filemap.Error: cannot open image file '.../wrlinux-image-std/1.0/deploy-wrlinux-image-std-image-complete/wrlinux-image-std-nxp-s32g.ext4.verity':
    [Errno 2] No such file or directory

Signed-off-by: Zhantao Tang <zhantao.tang@windriver.com>