nxp-s32g: pfe: replace sa_data with latest sa_data_min to fix build failure
Issue: LIN1023-4134

The kernel commit 4d3b2bd995ed ("net: dev: Convert sa_data to flexible array
in struct sockaddr") updated the sa_data member of sockaddr struct, so
update pfe related codes to keep align with kernel codes, or else there
will be following build errors:

  .../sw/linux-pfeng/pfeng-netif.c:1308:57: error: invalid application of 'sizeof' to incomplete type 'char[]'
  |  1308 |                         memset(&saddr.sa_data, 0, sizeof(saddr.sa_data));
  |       |                                                         ^

Signed-off-by: Zhantao Tang <zhantao.tang@windriver.com>