nxp-s32g: uboot: rename internal patch to fix QA issue for config_distro_bootcmd.h
Issue: LIN1024-8757

In nxp-s32g bsp layer, the uboot recipe has a internal patch:
  0001-include-config_distro_bootcmd.h-Check-go-before-boot.patch
which has the same name as one of oe-core layer. After the path:
    "${COREBASE}/meta/recipes-bsp/u-boot/files"
is prepended to FILESEXTRAPATHS for nxp-s32g uboot recipe, the same
name patch in oe-core layer will be used, but it is inconsistent with
nxp-s32g uboot codes, and will cause following fuzz issue:

  ERROR: QA Issue: Fuzz detected:
    checking file include/config_distro_bootcmd.h
    Hunk #1 succeeded at 496 with fuzz 1 (offset -39 lines).

So add nxp-s32g prefix to rename the nxp-s32g bsp layer's internale patch,
then the issue can be fixed.

Signed-off-by: Zhantao Tang <zhantao.tang@windriver.com>