nxp-s32g: linux: update to compatible with cvc bsp when build rt kernel
Issue: LIN1024-3359

The aptiv cvc bsp depends on nxp-s32g layer, so when build linux rt kernel,
the aptiv-cvc-131 machine name should be added into the contain condition,
or else, there will be following build error when compiling aptiv cvc
linux:

  make: Leaving directory '.../aptiv/dev/build-fix/tmp-glibc/work/cortexa53-wrs-linux/atf-s32g/2.10/git'
  | cp: cannot stat '.../tmp-glibc/work/cortexa53-wrs-linux/atf-s32g/2.10/recipe-sysroot/sysroot-only/fitImage': No such file or directory
  | WARNING: exit code 1 from a shell command.
  ERROR: Task (.../layers/nxp-s32g/recipes-bsp/arm-trusted-firmware/atf-s32g_2.10.bb:do_compile) failed with exit code '1'

Signed-off-by: Zhantao Tang <zhantao.tang@windriver.com>