nxp-s32g: NXP specific optee packages only support aarch64 platform
Issue: LIN1023-3325

In ./core/arch/arm/plat-s32/conf.mk file, the CFG_ARM64_core config
is enabled forcely for s32g platform. So when building optee-os and
optee-os-tadevkit packages in arm32 mode, there will be error reported
as below:
ERROR: lib32-optee-os-3.18.0 and lib32-optee-os-tadevkit-3.18.0 do_compile()
failed: CFG_ARM64_core and CFG_ARM32_core cannot be both 'y'.
Because optee-test, optee-client and optee-examples all depend on optee-os
and optee-os-tadevkit, add the 5 packages into NON_MULTILIB_RECIPES to avoid
building issue.

Signed-off-by: Meng Li <Meng.Li@windriver.com>