nxp-s32g: pkcs11-hse: add new demo apps for hse testing
Issue: LINUXEXEC-23037

There are some new demo apps for hse, so add them into rootfs.
And patch:
	0002-pkcs-fix-QA-error.patch

is added to fix the following QA error:

 ERROR: pkcs11-hse-1.0-r0 do_package_qa: QA Issue: File /usr/bin/hse-encrypt in package pkcs11-hse-examples doesn't have GNU_HASH (didn't pass LDFLAGS?)
 *File /usr/bin/hse-encrypt in package pkcs11-hse-examples doesn't have GNU_HASH (didn't pass LDFLAGS?)**
 **File /usr/bin/hse-sysimg in package pkcs11-hse-examples doesn't have GNU_HASH (didn't pass LDFLAGS?)*
 File /usr/bin/hse-sysimg in package pkcs11-hse-examples doesn't have GNU_HASH (didn't pass LDFLAGS?) [ldflags]
 ERROR: pkcs11-hse-1.0-r0 do_package_qa: Fatal QA errors were found, failing task.

Because the new added demo apps do not use the LDFLAGS when compiling, so add
LDFLAGS for them can fix the QA error.

Signed-off-by: Zhantao Tang <zhantao.tang@windriver.com>