u-boot-s32-tools: renamed to u-boot-tools
Issue: LIN1022-3867

After moving WRL_RECIPES from feature/default to layer.conf,
u-boot-s32-tools which is specific for nxp-s32g is visible for other
machines, such as bcm-2xxx-rpi4. And both u-boot-s32-tools under this
layer and u-boot-tools under oe-core will provide u-boot-tools-native,
this will cause error:
ERROR: Multiple .bb files are due to be built which each provide u-boot-tools-native:                                                                  | ETA:  0:00:02
  virtual:native:/build/layers/oe-core/meta/recipes-bsp/u-boot/u-boot-tools_2023.01.bb
  virtual:native:/build/layers/nxp-s32g/recipes-bsp/u-boot/u-boot-s32-tools_2020.04.bb

To avoid set PREFERRED_PROVIDER in almost each BSPs, renamed u-boot-s32-tools_2020.04
to u-boot-tools_2020.04-s32 to fix this issue

Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
Signed-off-by: Changqing Li <changqing.li@windriver.com>
Signed-off-by: Robert Yang <liezhi.yang@windriver.com>