nxp-s32g: linux: update to fix test signatures compatible failure
Issue: LIN1022-2921

The KERNEL_VERSION_SANITY_SKIP and SRCREV settings and internal patch:
  0001-Revert-modpost-turn-missing-MODULE_LICENSE-into-erro.patch
are all unneeded anymore.

So drop them, then the following test signatures error will be fixed too:

  INFO: test_signatures (common.CommonCheckLayer)
  INFO: ... FAIL
  INFO: Traceback (most recent call last): File ".../layers/oe-core/scripts/lib/checklayer/cases/common.py", ...
  AssertionError: Adding layer nxp-s32g changed signatures. 101 signatures changed, ...
  NOTE: Starting bitbake server... Dependency on checksum of file ./0001-Revert-modpost-turn-missing-MODULE_LICENSE-into-erro.patch was added

Signed-off-by: Zhantao Tang <zhantao.tang@windriver.com>