nxp-s32g: fix check layer issue of "Nothing PROVIDES 'atf-s32g'"
Issue: LIN1023-3068

This patch is to fix the following error when run yocto-check-layer:

  ERROR: Nothing PROVIDES 'atf-s32g'
  atf-s32g was skipped: incompatible with machine qemux86-64 (not in COMPATIBLE_MACHINE)
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'm7-sample', 'atf-s32g']

To fix the issue, add "COMPATIBLE_MACHINE = "^$"" in m7-sample.bb to set the
correct COMPATIBLE_MACHINE value.

Signed-off-by: Zhantao Tang <zhantao.tang@windriver.com>